<?php
//Do NOT edit this file
//To edit your configuration use web setup or
//copy this file to config.php and then edit config.php

/*Default Options Start*/
$default_options = array(
//General
'download_dir' => 'files/',
'download_dir_is_changeable' => false,
'delete_delay' => 0,
'rename_prefix' => '',
'rename_suffix' => '',
'bw_save' => true,
'file_size_limit' => 0,
//Authorization
'login' => false,
'users' => array('test' => 'test'),
//Presentation
'template_used' => 'plugmod',
'default_language' => 'en',
'show_all' => true,
'server_info' => true,
'ajax_refresh' => true,
//Actions Restrictions
'disable_actions' => false,
'disable_deleting' => false,
'disable_delete' => false,
'disable_rename' => false,
'disable_mass_rename' => false,
'disable_mass_email' => true,
'disable_email' => false,
'disable_ftp' => false,
'disable_upload' => false,
'disable_merge' => false,
'disable_split' => false,
'disable_tar' => false,
'disable_zip' => false,
'disable_unzip' => false,
'disable_rar' => false,
'disable_unrar' => false,
'disable_md5' => false,
'disable_list' => false,
//Advanced
'forbidden_filetypes' => array('.htaccess', '.htpasswd', '.php', '.php3', '.php4', '.php5', '.phtml', '.asp', '.aspx', '.cgi'),
'forbidden_filetypes_block' => false,
'rename_these_filetypes_to' => '.xxx',
'check_these_before_unzipping' => true,
'no_cache' => true,
'images_via_php' => false,
'redir' => true,
'fgc' => 0
);
/*Default Options End*/
?>